### ISSUE TITLE
helm install --debug k-rail k-rail/k-rail --namespace k-rail fails

### ISSUE THREAD

**Issue by csgyuri** [cruise-automation/k-rail#117]
I am trying to install k-rail 3.4.2 by following the below steps and the installation fails:

**Steps to reproduce**
helm repo add k-rail https://cruise-automation.github.io/k-rail/
helm repo update

kubectl create namespace k-rail
kubectl label namespace k-rail k-rail/ignore=true

helm install k-rail k-rail/k-rail --namespace k-rail

The version being installed is 3.4.2

**Expected results**
k-rail installed

**Actual results**
helm install --debug k-rail k-rail/k-rail --namespace k-rail
install.go:173: [debug] Original chart version: ""
Error: failed to fetch https://github.com/cruise-automation/k-rail/releases/download/k-rail-v3.4.2/k-rail-v3.4.2.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://github.com/cruise-automation/k-rail/releases/download/k-rail-v3.4.2/k-rail-v3.4.2.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:90
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:42
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:704
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:185
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371

I checked the releases and up to 3.4.1 and there is a k-rail-3.4.1, but there is none for 3.4.2

**Comment by EddieKSpin** [comment]
seems the link is wrong 
github link is https://github.com/cruise-automation/k-rail/releases/download/v3.4.2/v3.4.2.tgz

**Comment by dkiser** [comment]
Thank you for brining this to our attention.  The https://github.com/cruise-automation/k-rail/releases/download/k-rail-v3.4.2/k-rail-v3.4.2.tgz  link should now be fixed.  We will be updating our release process to prevent this in the future.
