### ISSUE TITLE
Upload helm charts to a repo?

### ISSUE THREAD

**Issue by drnic** [cruise-automation/k-rail#2]
Could the helm chart releases be uploaded to a helm repo?

(We run chartmuseum on https://run.pivotal.io + behind the scenes host the charts on s3 via https://github.com/starkandwayne/chartmuseum-for-cloudfoundry)

**Comment by dustin-decker** [comment]
We've not yet used Helm 3 (which does not use Tiller), so we have only provided `helm template` instructions for installation: https://github.com/cruise-automation/k-rail#installation

Can you confirm if the `helm template` pattern works with a helm repo, or if the chart is compatible with Helm 3?

**Comment by funkypenguin** [comment]
I can confirm the above - we install all our helm charts using a (complicated) `helm template` process to produce the YAMLs, and then inject them into K8s. I've created https://github.com/cruise-automation/k-rail/pull/20 to make a published chart available until you setup your own repo. 

(I publish mine using this workflow: https://github.com/int128/helm-github-pages)

**Comment by frenchi** [comment]
Blocked by #51
