### ISSUE TITLE
Revisit policy configuration: fail faster

### ISSUE THREAD

**Issue by alpe** [cruise-automation/k-rail#39]
Following up on: https://github.com/cruise-automation/k-rail/issues/36#issuecomment-557364831

The `policy.Config` is passed to the policy implementations with an admission request. There is currently no way to fail fast on configuration issues. For example:  `MaximumSizeLimit < DefaultSizeLimit` . 
Some options to address this:
- Add some custom Validate function and fail after parsing yaml . Problem may persist that type conversion from human readable string to system type has to be done on ever call.
- Use constructor for policies and validate + store config with object
- Use  https://github.com/kubernetes-sigs/yaml parser so that unmarshall method can be customized. For example [k8s.Quantity](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go)  can be used to build #36  . This would require to replace the `yaml:` annotation with `json:`

To come up with a good proposal it would be helpful to understand how configuration changes should be handled in the future. Like update config and restart like now or with a watchdog.

**Comment by dustin-decker** [comment]
The deployment supports zero downtime deploys so I'm favoring update config and restart for simplicity. I am open to a watchdog approach for more flexibility though.

Option 3 (k8s yaml parser) seems pretty slick and easy. A constructor could still be used if more validation or setup is needed.

**Comment by alpe** [comment]
👍 This is how the config validation will look like now with the new yaml parser. 
```
type MutateEmptyDirSizeLimit struct {
	MaximumSizeLimit apiresource.Quantity `json:"maximum_size_limit"`
	DefaultSizeLimit apiresource.Quantity `json:"default_size_limit"`
}

func (m *MutateEmptyDirSizeLimit) UnmarshalJSON(value []byte) error {
	var v map[string]json.RawMessage
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}

	if max, ok := v["maximum_size_limit"]; ok {
		if err := m.MaximumSizeLimit.UnmarshalJSON(max); err != nil {
			return fmt.Errorf("maximum_size_limit failed: %s", err)
		}
	}
	if def, ok := v["default_size_limit"]; ok {
		if err := m.DefaultSizeLimit.UnmarshalJSON(def); err != nil {
			return fmt.Errorf("default_size_limit failed: %s", err)
		}
	}
	if m.DefaultSizeLimit.IsZero() {
		return errors.New("default size must not be empty")
	}
	if m.MaximumSizeLimit.IsZero() {
		return errors.New("max size must not be empty")
	}
	if m.DefaultSizeLimit.Cmp(m.MaximumSizeLimit) > 0 {
		return errors.New("default size must not be greater than max size")
	}
	return nil
}
```
See: https://github.com/cruise-automation/k-rail/pull/40/commits/186b1f3d9380e5ac513fc472760ae1d483cb4a75#diff-289683e4d5e123c054950ec3c01607a4R42
