### ISSUE TITLE
[FR] Emergency stop button. Prevent all changes when toggled.

### ISSUE THREAD

**Issue by dustin-decker** [cruise-automation/k-rail#56]
Some incidents require preventing changes being made. During degraded performance, prevent further degregation or thundering herd after recovery.

**Comment by dustin-decker** [comment]
This should be possible to toggle without redeploys, since that is not always possible during degraded state.

**Comment by alpe** [comment]
🤔I am not sure if this should go into the admission hook. The scheduler should respect the
[Priority class](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass) of the pods and only terminate the ones with lower priority to make resources available. If you are preventing modifications you are basically sabotaging an intended behaviour and core feature of the scheduler.

Btw. the helm chart does not contain a `PriorityClass`. We better make that a high value 📈

**Comment by dustin-decker** [comment]
I think you are right. This could only be implemented by excluding all of the namespaces with components required by the platform (kube-system, monitoring, ingress, etc) so it would probably be an easy footgun. 

That said, priority class isn't enough sometimes when there is an underlying etcd issue or similar. 

I'll close this.
