### ISSUE TITLE
Can we use regexs in exemptions?

### ISSUE THREAD

**Issue by funkypenguin** [cruise-automation/k-rail#67]
Hey guys,

I find myself needing to allow users to exec into pods in specific namespaces. Problem is, I don't know exactly what those namespaces will be called, ahead of time, but I know that they'll always be prefixed with `preview-`.

Is it possible to permit regex matches for fields in exceptions?

Thanks!
David

**Comment by dustin-decker** [comment]
Regex is not supported, but glob matching is! Just set the resource name as `preview-*`. A trailing glob is automatically appended to the resource name if not provided since some resources create sub resources with suffixes. Any exemption field not provided is also assumed to match all.

**Comment by funkypenguin** [comment]
Perfect, than you :)
