### ISSUE TITLE
Pod policy check inconsistencies

### ISSUE THREAD

**Issue by js-timbirkett** [cruise-automation/k-rail#81]
Hi 👋 

There seems to be inconsistencies in how policies are checked on pod specs (possibly others). For example, the policy for `No ShareProcessNamespace` checks if the value is not `nil`:
https://github.com/cruise-automation/k-rail/blob/b6763dd01d87d5b4fef43c47dd589c83c6616789/policies/pod/no_shareprocessnamespace.go#L41

Whilst the policy for `No Host Network` (sic) checks if the value is `true`.
https://github.com/cruise-automation/k-rail/blob/b6763dd01d87d5b4fef43c47dd589c83c6616789/policies/pod/no_host_network.go#L41

Checking against `nil` will cause the policy to fire if I explicitly set `shareProcessNamespace: false`. It also fires if some tooling explicitly sets the value to `false`. Terraform does this in it's `kubernetes_deployment` resource and K-Rail denies the deployment.

Is there a reason for checking `nil` rather than `true`? Or is it just something that crept in and may be considered a 🦋 (bug)?

I'm willing to open a PR and tests once I understand the why (if it was a conscious decision) 😄 - Thanks!

**Comment by dustin-decker** [comment]
Thanks for the report. The nil check is because it is a pointer and it is possible for it to be nil, true, or false.
It should check for nil and then the bool.

So,

```if podResource.PodSpec.ShareProcessNamespace != nil && podResource.PodSpec.ShareProcessNamespace {```

**Comment by dustin-decker** [comment]
Fixed in https://github.com/cruise-automation/k-rail/releases/tag/v2.1.0 by #82

Thank you

**Comment by js-timbirkett** [comment]
Awesome, thanks for the quick release @dustin-decker 😄
